[database]
host = localhost
port = 5432
database = tasks_db
user = postgres
password = postgres


[data]
# Any fields in the data section are available in migration templates
# prefix = foo
